  services:
    db:
      image: postgres:latest
      container_name: db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: toDobd
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - app_network

    server:
      build: ./server
      container_name: server
      environment:
        DB_NAME: toDobd
        DB_USER: postgres
        DB_PASSWORD: root
        DB_HOST: db
        DB_PORT: 5432
      ports:
        - "7000:7000"
      depends_on:
        - db
      networks:
        - app_network

    client:
      build: ./client
      container_name: client
      ports:
        - "3000:3000"
      depends_on:
        - server
      networks:
        - app_network

  volumes:
    postgres_data:

  networks:
    app_network:
      driver: bridge
